Data Processing - Population Data

In [3]:
import pandas as pd

In [5]:
# reading the CSV file
csvFile = pd.read_csv('tmp.csv')

In [6]:
csvFile.head()

  Province (10 thousand);Population;Male;Female;<15;15-64;>65;Above chollege;High school;Junior high school;Primary school
0  Beijing;2189.3;1119.6;1069.7;259.2;1638.9;291....
1  Chongqing;3205.4;1620.3;1585.1;510.0;2147.9;54...
2  Shanghai;2487.1;1287.6;1199.5;243.7;1838.5;404...
3  Tianjin;1386.6;714.5;672.1;186.8;995.3;204.5;3...
4  Anhui;6102.7;3110.6;2992.2;1174.2;4012.5;916.0...

In [7]:
#change column name as 'col'
csvFile.columns = ['col']

In [8]:
csvFile.columns

Index(['col'], dtype='object')

In [15]:
# split 'col' into multiple columns

split_columns_adjusted = [
    "Province", "Population", "Male", "Female", "<15", "15-64", ">65", "College and Above", "Senior Secondary School", "Junior Secondary School", "Primary School"
]

df_split_adjusted = csvFile["col"].str.split(";", expand=True)
df_split_adjusted = df_split_adjusted.iloc[:, :len(split_columns_adjusted)]
df_split_adjusted.columns = split_columns_adjusted

df_split_adjusted

,Province,Population,Male,Female,<15,15-64,>65,College and Above,Senior Secondary School,Junior Secondary School,Primary School
0,Beijing,2189.3,1119.6,1069.7,259.2,1638.9,291.2,919.1,385.2,509.9,229.9
1,Chongqing,3205.4,1620.3,1585.1,510.0,2147.9,547.5,494.0,511.5,980.3,958.2
2,Shanghai,2487.1,1287.6,1199.5,243.7,1838.5,404.9,842.4,473.0,719.6,296.7
3,Tianjin,1386.6,714.5,672.1,186.8,995.3,204.5,373.6,245.7,447.8,223.6
4,Anhui,6102.7,3110.6,2992.2,1174.2,4012.5,916.0,810.4,811.3,2058.1,1640.1
5,Fujian,4154.0,2146.8,2007.2,802.6,2890.4,461.1,587.7,590.4,1338.3,1164.4
6,Gansu,2502.0,1270.0,1232.0,485.4,1701.8,314.7,362.9,323.7,686.1,745.8
7,Guangdong,12601.3,6687.5,5913.8,2375.3,9144.7,1081.2,1978.3,2296.5,4471.4,2605.4
8,Guangxi,5012.7,2591.6,2421.1,1184.5,3216.6,611.5,541.7,649.7,1824.0,1396.3
9,Guizhou,3856.2,1970.5,1885.7,924.3,2486.1,445.8,422.3,383.7,1174.8,1230.9
10,Hainan,1008.1,534.5,473.6,201.3,701.7,105.1,140.3,156.9,405.0,198.6
11,Hebei,7461.0,3767.8,3693.2,1508.6,4913.8,1038.6,926.5,1034.2,2980.7,1840.2
12,Heilongjiang,3185.0,1595.4,1589.6,328.7,2359.1,497.2,471.2,494.5,1363.0,696.3
13,Henan,9936.6,4983.2,4953.4,2299.3,6296.8,1340.4,1166.9,1514.2,3728.0,2440.1
14,Hubei,5775.3,2969.6,2805.6,941.9,3990.7,842.6,895.3,1006.5,1979.8,1358.3
15,Hunan,6644.5,3399.3,3245.2,1297.0,4363.4,984.0,813.2,1181.1,2367.8,1675.3
16,InnerMongolia,2404.9,1227.5,1177.4,337.7,1753.4,313.8,449.4,356.3,814.3,568.2
17,Jiangsu,8474.8,4303.5,4171.3,1289.0,5812.9,1372.9,1581.7,1372.2,2822.8,1927.3
18,Jiangxi,4518.9,2331.7,2187.1,992.3,2989.2,537.3,537.6,684.4,1604.2,1243.3
19,Jilin,2407.3,1201.7,1205.6,281.9,1749.7,375.8,402.9,411.2,920.4,537.3
20,Liaoning,4259.1,2126.2,2133.0,473.6,3043.6,741.9,775.8,624.8,1822.9,804.5
21,Ningxia,720.3,366.9,353.4,146.8,504.2,69.3,124.9,96.7,214.0,188.1
22,Qinghai,592.4,303.4,289.0,123.3,417.7,51.4,88.1,62.6,144.2,193.9
23,Shaanxi,3952.9,2022.7,1930.2,685.0,2741.3,526.5,727.2,615.9,1343.2,857.2
24,Shandong,10152.7,5143.4,5009.4,1906.7,6709.9,1536.1,1460.4,1455.3,3632.4,2405.5
25,Shanxi,3491.6,1780.3,1711.2,570.9,2470.3,450.4,606.1,575.6,1360.0,681.1
26,Sichuan,8367.5,4228.9,4138.6,1347.2,5603.7,1416.6,1110.1,1113.0,2631.0,2620.4
27,Tibet,364.8,191.3,173.5,89.5,254.6,20.7,40.2,25.7,57.5,117.1
28,Xinjiang,2585.2,1335.5,1249.7,580.6,1804.0,200.6,427.5,341.5,815.9,734.3
29,Yunnan,4720.9,2442.1,2278.8,923.9,3289.5,507.5,547.7,488.0,1380.4,1683.8
30,Zhejiang,6456.8,3367.8,3088.9,868.4,4731.5,856.8,1097.0,939.8,2111.7,1703.6

In [10]:
df_split_adjusted.dtypes

Province      object
Population    object
Male          object
Female        object
<15           object
15-64         object
>65           object
dtype: object

In [16]:
# Converting columns from object to float
df_split_adjusted["Province"] = df_split_adjusted["Province"].astype(str)
df_split_adjusted["Population"] = df_split_adjusted["Population"].astype(float)
df_split_adjusted["Male"] = df_split_adjusted["Male"].astype(float)
df_split_adjusted["Female"] = df_split_adjusted["Female"].astype(float)
df_split_adjusted["<15"] = df_split_adjusted["<15"].astype(float)
df_split_adjusted["15-64"] = df_split_adjusted["15-64"].astype(float)
df_split_adjusted[">65"] = df_split_adjusted[">65"].astype(float)
df_split_adjusted["College and Above"] = df_split_adjusted["College and Above"].astype(float)
df_split_adjusted["Senior Secondary School"] = df_split_adjusted["Senior Secondary School"].astype(float)
df_split_adjusted["Junior Secondary School"] = df_split_adjusted["Junior Secondary School"].astype(float)
df_split_adjusted["Primary School"] = df_split_adjusted["Primary School"].astype(float)




df_split_adjusted.dtypes

Province                    object
Population                 float64
Male                       float64
Female                     float64
<15                        float64
15-64                      float64
>65                        float64
College and Above          float64
Senior Secondary School    float64
Junior Secondary School    float64
Primary School             float64
dtype: object

In [17]:
df_split_adjusted.to_excel("new_population.xlsx")